### ISSUE TITLE
建议增加Token的强制刷新和异常捕获

### ISSUE THREAD

**Issue by lyt8384** [aobozhang/easemob-facades#8]
`Token`经常会失效，可否新增下强制刷新的处理？
最新的环信Demo里面`postCurl`里取消了状态的返回，导致非`200`的状况不能被当作异常的处理了。可否重写这块逻辑？
Thx

**Comment by aobozhang** [comment]
已经在dev版本中增加了 401 (token校验失败) 的异常处理；
因为我这里的环境并不能复现有关token失效的问题；
（7天是很长的一段时间，在getToken中设置的cache缓存机制是1天超时后再次获取）

如果使用dev版本测试仍然有问题，请尝试重新定位问题或者再留言；
（或者能够定位反馈值不是401而是其他，那就不是token的问题了）

**Comment by lyt8384** [comment]
实际上我在一个独立项目的生产环境下，`chatmessages`接口在较高频率(大约每1.5秒1次)工作状况下。每分钟都会出现401。是个很奇怪的现象。需要重跑`getToken`获取最新`Token`。

还有生产环境下，`40X`的错误也是有一定比例的。例如注册和发信相关接口。
在很早很早的Demo中，还是可以看到的，后来不知为何被弃用了

``` php
$res ['status'] = curl_getinfo ( $curl, CURLINFO_HTTP_CODE );
```

**Comment by aobozhang** [comment]
## 怀疑是GetToken没有缓存，或者缓存失效。

在我的环境中，通过 <code> laravel schedule </code> 每分钟递归调用  

``` php
Easemob::getChatRecordForPage($ql, 50, $cursor)  
// 获取所有自上次拉取,到现在为止的所有数据;  
```

稳定运行了好久，到现在为止还没出现过其他错误码

（´◔ ₃ ◔`)

**Comment by lyt8384** [comment]
(ˉ﹃ˉ) 看来我需要找下环信的人了。
不是缓存失效，其实每次401后我们都会记录当前Token，然后重试1次，如果依旧401，那么就刷新。
